---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: python-demo
spec:
  secretName: python-crt-secret
  dnsNames:
  - pythonapp.cxcto.cisco.com
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  
---
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  name: python-ingress
  namespace: python-demo
spec:
  deployment:
    metadata:
      labels:
        gateway-name: argo-ingress
        gateway-type: ingress
    replicas:
      count: 1
      min: 1
      max: 1
  service:
    ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 8000
    type: LoadBalancer
  istioControlPlane:
    name: cp-v111x
    namespace: istio-system 
  type: ingress

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: python-gateway
  namespace: python-demo
spec:
  selector:
    gateway-name: python-ingress
    gateway-type: ingress
  servers:
  - port:
      number: 8001
      name: http
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: python-crt-secret
    hosts:
    - "pythonapp.cxcto.cisco.com"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: python-server
  namespace: python-demo
spec:
  hosts:
  - "pythonapp.cxcto.cisco.com"
  gateways:
  - python-gateway
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: python-app.python-demo.svc.cluster.local
