---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: test-app
spec:
  secretName: testapp-crt-secret
  dnsNames:
  - testapp.cxcto-staging.cisco.com
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  
---
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  name: testapp-ingress
  namespace: test-app
spec:
  deployment:
    metadata:
      labels:
        gateway-name: testapp-ingress
        gateway-type: ingress
    replicas:
      count: 1
      min: 1
      max: 1
  service:
    ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 8000
    type: LoadBalancer
  istioControlPlane:
    name: cp-v111x
    namespace: istio-system 
  type: ingress

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: testapp-gateway
  namespace: test-app
spec:
  selector:
    gateway-name: testapp-ingress
    gateway-type: ingress
  servers:
  - port:
      number: 8000
      name: http
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: testapp-crt-secret
    hosts:
    - "testapp.cxcto-staging.cisco.com"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: testapp-server
  namespace: test-app
spec:
  hosts:
  - "testapp.cxcto-staging.cisco.com"
  gateways:
  - testapp-gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: test-app.test-app.svc.cluster.local
